NDefines_Graphics.NMapMode.CONSTRUCTION_MAP_MODE_BUILDING_LEVEL_LOW_COLOR = { 0.2, 0.7, 0.0, 0.1 }
NDefines_Graphics.NMapMode.CONSTRUCTION_MAP_MODE_BUILDING_LEVEL_HI_COLOR = { 0.4, 0.9, 0.0, 0.8 }
NDefines_Graphics.NMapMode.FACTIONS_COLOR_NOT_MEMBER = { 0.6, 0.6, 0.6, 0.25 }
NDefines_Graphics.NMapMode.SUPPLY_AREAS_PRIORITY_ADJACENCY_RULE = 3
NDefines_Graphics.NGraphics.TRADE_ROUTE_SUPPLIES_TRANSFER_COLOR = { 1.0, 1.0, 1.0, 0.75 }
NDefines_Graphics.NGraphics.NAVAL_MISSION_ICONS_DISTANCE_CUTOFF = 900
